var R=require("../../../../../../../chunks/[turbopack]_runtime.js")("server/app/api/cars/[carId]/checks/[checkId]/report.pdf/route.js")
R.c("server/chunks/node_modules_next_bbf8d79a._.js")
R.c("server/chunks/node_modules_undici_lib_dispatcher_cc7d29a0._.js")
R.c("server/chunks/node_modules_undici_lib_llhttp_74c2e85b._.js")
R.c("server/chunks/node_modules_undici_lib_web_220e9cec._.js")
R.c("server/chunks/node_modules_undici_lib_c0b38388._.js")
R.c("server/chunks/node_modules_undici_index_0304e24d.js")
R.c("server/chunks/node_modules_html2canvas_dist_html2canvas_esm_178f5bb6.js")
R.c("server/chunks/node_modules_core-js_bf3fc61c._.js")
R.c("server/chunks/node_modules_canvg_lib_index_cjs_84557b9a._.js")
R.c("server/chunks/6b4ca_pako_dist_pako_esm_mjs_f2f37c92._.js")
R.c("server/chunks/node_modules_jspdf_dist_jspdf_node_min_2f7aa471.js")
R.c("server/chunks/node_modules_ab5e138e._.js")
R.c("server/chunks/[root-of-the-server]__8d24721e._.js")
R.c("server/chunks/ce889_server_app_api_cars_[carId]_checks_[checkId]_report_pdf_route_actions_56c4ef9c.js")
R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/cars/[carId]/checks/[checkId]/report.pdf/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/cars/[carId]/checks/[checkId]/report.pdf/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
